# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'homeostasie'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Cahier de texte
    submenu:
      - name: "Quatrième : 4e1 - 4e2"
        link: /cahier-de-texte/4-quatrieme
      - name: "Troisième : 3e1 - 3e3 - 3e5"
        link: /cahier-de-texte/3-troisieme
  - name: "Cours et exercices"
    submenu:
      - name: "Quatrième : 4e1 - 4e2"
        link: /documents/4-quatrieme
      - name: "Troisième : 3e1 - 3e3 - 3e5"
        link: /documents/3-troisieme
  - name: Ressources
    link: /ressources     
  - name: "Une question ?"
    submenu:
      - name: Pearltrees
        icon: pearltrees
        link: https://www.pearltrees.com/tlafond   
      - name: "Rendre du travail"
        icon: rendre
        link: /rendu
      - name: "Poser une question"
        icon: question
        link: /questions  
      - name: Colophon
        icon: colophon
        link: /colophon
      - name: GitHub
        icon: github
        link: http://github.com/homeostasie


    
