# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'homeostasie'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Cahier de texte
    submenu:
      - name: "Cinquieme : 5e1 - 5e2 - 5e5"
        link: /cahier-de-texte/5-cinquieme
      - name: "Troisième : 3e1 - 3e2 - 3e3"
        link: /cahier-de-texte/3-troisieme
  - name: "Cours et exercices"
    submenu:
      - name: "Cinquieme : 5e1 - 5e2 - 5e5"
        link: /documents/5-cinquieme
      - name: "Troisième : 3e1 - 3e2 - 3e3"
        link: /documents/3-troisieme
      - name: Ressources
        link: /ressources   
  - name: "Une question ?"
    submenu:
      - name: Pearltrees
        icon: pearltrees
        link: https://www.pearltrees.com/tlafond   
      - name: "Rendre du travail"
        link: /rendu
      - name: "Poser une question"
        link: /questions  
      - name: Colophon
        link: /colophon
      - name: GitHub
        icon: github
        link: http://github.com/homeostasie


    
